"""empty message

Revision ID: fdc94a0c3472
Revises: bdb225212ae9
Create Date: 2021-09-28 22:32:51.550711

"""
print("mako")
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc94a0c3472'
down_revision = 'bdb225212ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
